- name: DNF update the system
  dnf:
    name:  "*"
    state: latest
    exclude: nginx
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '8'

- name: Yum update the system
  yum:
    name: "*"
    state: latest
    exclude: nginx
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] <= '7'

- name: See if an instance needs a reboot
  ansible.builtin.command: needs-restarting -r
  register: reboot_required
  ignore_errors: true
  failed_when: false
  changed_when: reboot_required.rc != 0
  when: ansible_facts['os_family'] == 'RedHat'
  notify:
    - Reboot system